// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.lastAppBuildId", "20251118022223");
user_pref("extensions.lastAppVersion", "145.0.1");
user_pref("extensions.lastPlatformVersion", "145.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"45485174-fb38-4a27-ae44-a0fa68ddd847\",\"formautofill@mozilla.org\":\"112f02ba-3aa1-40d6-ad2e-51e390530b7b\",\"ipp-activator@mozilla.com\":\"6fd1dfef-9a67-4ef3-b382-8b2d1e9eafec\",\"pictureinpicture@mozilla.org\":\"f5d5c8eb-6228-4a4a-b344-848ba65b6b6d\",\"addons-search-detection@mozilla.com\":\"b74128d4-ad9a-49cd-baaf-a8ee820a5fad\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"ebea03fb-f783-44e2-9699-094cccb7e2bb\"}");
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("sanity-test.device-id", "0x46a8");
user_pref("sanity-test.driver-version", "32.0.101.7082");
user_pref("sanity-test.running", true);
user_pref("sanity-test.version", "20251118022223");
